spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/myblog?serverTimezone=Asia/Seoul
    username: root
    password: lysi070511@
  jpa:
#    database-platform: org.hibernate.dialect.MySQL8InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        highlight_sql: true
        format_sql: true
  output:
    ansi:
      enabled: always
  logging:
    level:
      org:
        hibernate:
          SQL: DEBUG
          type:
            descriptor:
              sql:
                BasicBinder: TRACE
        springframework:
          orm:
            jpa: DEBUG